create table if not exists public.game_players (
  id bigint generated by default as identity primary key,
  nickname text not null unique,
  created_at timestamptz not null default now(),
  constraint game_players_nickname_length_check check (char_length(btrim(nickname)) between 2 and 24)
);

create table if not exists public.game_results (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.game_players(id) on delete cascade,
  game_key text not null,
  difficulty text,
  score integer,
  combo integer,
  duration_seconds integer,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint game_results_game_key_check check (game_key in ('minesweeper', 'brick_breaker', 'neon_flow')),
  constraint game_results_difficulty_check check (
    (game_key = 'minesweeper' and difficulty in ('easy', 'medium', 'hard'))
    or
    (game_key = 'brick_breaker' and difficulty is null)
    or
    (game_key = 'neon_flow' and difficulty in ('easy', 'medium', 'hard', 'expert'))
  ),
  constraint game_results_non_negative_check check (
    coalesce(score, 0) >= 0
    and coalesce(combo, 0) >= 0
    and coalesce(duration_seconds, 0) >= 0
  ),
  constraint game_results_required_values_check check (
    (game_key = 'minesweeper' and duration_seconds is not null and score is null and combo is null)
    or
    (game_key = 'brick_breaker' and score is not null and combo is not null and duration_seconds is null)
    or
    (game_key = 'neon_flow' and score is not null and duration_seconds is not null and combo is null)
  )
);

alter table public.game_results add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table public.game_results drop constraint if exists game_results_game_key_check;
alter table public.game_results add constraint game_results_game_key_check check (game_key in ('minesweeper', 'brick_breaker', 'neon_flow'));
alter table public.game_results drop constraint if exists game_results_difficulty_check;
alter table public.game_results add constraint game_results_difficulty_check check (
  (game_key = 'minesweeper' and difficulty in ('easy', 'medium', 'hard'))
  or
  (game_key = 'brick_breaker' and difficulty is null)
  or
  (game_key = 'neon_flow' and difficulty in ('easy', 'medium', 'hard', 'expert'))
);
alter table public.game_results drop constraint if exists game_results_required_values_check;
alter table public.game_results add constraint game_results_required_values_check check (
  (game_key = 'minesweeper' and duration_seconds is not null and score is null and combo is null)
  or
  (game_key = 'brick_breaker' and score is not null and combo is not null and duration_seconds is null)
  or
  (game_key = 'neon_flow' and score is not null and duration_seconds is not null and combo is null)
);

alter table public.game_players enable row level security;
alter table public.game_results enable row level security;

drop policy if exists "Game players are readable" on public.game_players;
create policy "Game players are readable"
  on public.game_players for select
  using (true);

drop policy if exists "Anyone can create game players" on public.game_players;
create policy "Anyone can create game players"
  on public.game_players for insert
  with check (char_length(btrim(nickname)) between 2 and 24);

drop policy if exists "Game results are readable" on public.game_results;
create policy "Game results are readable"
  on public.game_results for select
  using (true);

drop policy if exists "Anyone can create game results" on public.game_results;
create policy "Anyone can create game results"
  on public.game_results for insert
  with check (
    exists (
      select 1
      from public.game_players
      where game_players.id = game_results.player_id
    )
    and game_key in ('minesweeper', 'brick_breaker', 'neon_flow')
    and (
      (game_key = 'minesweeper' and difficulty in ('easy', 'medium', 'hard'))
      or
      (game_key = 'brick_breaker' and difficulty is null)
      or
      (game_key = 'neon_flow' and difficulty in ('easy', 'medium', 'hard', 'expert'))
    )
    and coalesce(score, 0) >= 0
    and coalesce(combo, 0) >= 0
    and coalesce(duration_seconds, 0) >= 0
  );

do $$
begin
  if to_regclass('public.game_player_stats') is not null then
    execute 'drop policy if exists "Anyone can update game player stats" on public.game_player_stats';
    execute 'drop policy if exists "Anyone can create game player stats" on public.game_player_stats';
    execute 'drop policy if exists "Game player stats are readable" on public.game_player_stats';
  end if;
end $$;

create or replace view public.minesweeper_leaderboard
with (security_invoker = true) as
select
  min(gr.id) as id,
  gp.nickname,
  gr.difficulty,
  min(gr.duration_seconds) as time_seconds,
  count(*)::integer as games_played,
  min(gr.created_at) as created_at,
  max(gr.created_at) as updated_at
from public.game_results gr
join public.game_players gp on gp.id = gr.player_id
where gr.game_key = 'minesweeper'
group by gp.id, gp.nickname, gr.difficulty;

create or replace view public.brick_breaker_leaderboard
with (security_invoker = true) as
select
  min(gr.id) as id,
  gp.nickname,
  max(gr.score) as score,
  max(gr.combo) as best_combo,
  count(*)::integer as games_played,
  min(gr.created_at) as created_at,
  max(gr.created_at) as updated_at
from public.game_results gr
join public.game_players gp on gp.id = gr.player_id
where gr.game_key = 'brick_breaker'
group by gp.id, gp.nickname;

create or replace view public.neon_flow_leaderboard
with (security_invoker = true) as
select distinct on (gp.id, gr.difficulty)
  gp.nickname,
  gr.difficulty,
  gr.score as best_score,
  gr.duration_seconds as best_time_seconds,
  coalesce((gr.metadata->>'moves')::integer, 0) as best_moves,
  count(*) over (partition by gp.id, gr.difficulty)::integer as games_played,
  gr.created_at
from public.game_results gr
join public.game_players gp on gp.id = gr.player_id
where gr.game_key = 'neon_flow'
order by gp.id, gr.difficulty, gr.score desc, gr.duration_seconds asc, coalesce((gr.metadata->>'moves')::integer, 0) asc, gr.created_at asc;

create or replace view public.player_global_stats
with (security_invoker = true) as
select
  gp.id,
  gp.nickname,
  count(gr.id)::integer as total_games_played,
  count(gr.id) filter (where gr.game_key = 'minesweeper')::integer as minesweeper_games_played,
  min(gr.duration_seconds) filter (where gr.game_key = 'minesweeper' and gr.difficulty = 'easy') as minesweeper_easy_best_seconds,
  min(gr.duration_seconds) filter (where gr.game_key = 'minesweeper' and gr.difficulty = 'medium') as minesweeper_medium_best_seconds,
  min(gr.duration_seconds) filter (where gr.game_key = 'minesweeper' and gr.difficulty = 'hard') as minesweeper_hard_best_seconds,
  count(gr.id) filter (where gr.game_key = 'brick_breaker')::integer as brick_breaker_games_played,
  coalesce(max(gr.score) filter (where gr.game_key = 'brick_breaker'), 0) as brick_breaker_best_score,
  coalesce(max(gr.combo) filter (where gr.game_key = 'brick_breaker'), 0) as brick_breaker_best_combo,
  count(gr.id) filter (where gr.game_key = 'neon_flow')::integer as neon_flow_games_played,
  coalesce(max(gr.score) filter (where gr.game_key = 'neon_flow'), 0) as neon_flow_best_score,
  gp.created_at,
  coalesce(max(gr.created_at), gp.created_at) as updated_at
from public.game_players gp
left join public.game_results gr on gr.player_id = gp.id
group by gp.id, gp.nickname, gp.created_at;

create index if not exists game_players_nickname_idx on public.game_players (lower(nickname));
create index if not exists game_results_player_id_idx on public.game_results (player_id);
create index if not exists game_results_minesweeper_idx on public.game_results (difficulty, duration_seconds) where game_key = 'minesweeper';
create index if not exists game_results_brick_breaker_idx on public.game_results (score desc, combo desc) where game_key = 'brick_breaker';
create index if not exists game_results_neon_flow_idx on public.game_results (difficulty, score desc, duration_seconds) where game_key = 'neon_flow';

grant usage on schema public to anon, authenticated;
grant select, insert on public.game_players to anon, authenticated;
grant select, insert on public.game_results to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
grant select on public.minesweeper_leaderboard to anon, authenticated;
grant select on public.brick_breaker_leaderboard to anon, authenticated;
grant select on public.neon_flow_leaderboard to anon, authenticated;
grant select on public.player_global_stats to anon, authenticated;
